1.3. Применить метод простых итераций и метод Зейделя к решению СЛАУ, задавая в качестве входных данных матрицу системы, вектор правых частей и точность вычислений. Проанализировать количество итераций, необходимое для достижения заданной точности.

# Оформление

In [114]:
A = [[24, 2, 4,-9], [-6, -27, -8, -6], [-4, 8, 19, 6], [4, 5, -3, -13]]
B = [-9, -76, -79, -70]

In [115]:
import numpy as np
matrix = np.array(A)
b = np.array(B)
n = 4

## Описательная часть

In [117]:
# перевод значений вектора b в тип данных float
def floating_b(m):
    b = []
    for i in m:
        b.append(float(i))
    return np.array(b)
# good working

In [118]:
# перевод значений матрицы matrix в тип данных float
def floating_a(mrx):

    m = []
    for i in mrx:
        temp = []
        for j in i:
            temp.append(float(j))
        m.append(temp)
    np.array(m)
    
    return np.array(m)
# good working

In [119]:
# We get betta-vector
def betta(b):
    b = floating_b(b)
    for i in range(n):
        b[i] /= matrix[i][i]
    return b

In [120]:
# We get alpha-matrix
def alpha(matrix):
    matrix = floating_a(matrix)
    for i in range(n):
        matrix[i] = matrix[i] / (-matrix[i][i])
        matrix[i][i] = 0
    return matrix

In [121]:
# сравнивается норма dx и заданная точность
def norma(x, x_prev, epsilon):
    nma = (sum((x - x_prev) ** 2)) ** 0.5
    if nma > epsilon:
        return True
    else: return (x, nma)

In [122]:
# copy of b-vector
def copy_b(b):
    b_copy = []
    for i in b:
        b_copy.append(i)
    return b_copy
# В сравнении с ручным счетом работает стабильно

## Часть,  выводящая решение

In [123]:
alpha(matrix)

array([[ 0.        , -0.08333333, -0.16666667,  0.375     ],
       [-0.22222222,  0.        , -0.2962963 , -0.22222222],
       [ 0.21052632, -0.42105263,  0.        , -0.31578947],
       [ 0.30769231,  0.38461538, -0.23076923,  0.        ]])

In [124]:
betta(b)

array([-0.375     ,  2.81481481, -4.15789474,  5.38461538])

In [125]:
# Задание нового вектора b должно быть обязательно перед объявлением новой матрицы "a" в том случае,
# если мы создаем не новую переменную 'a', а меняем старую (matrix), то есть строка 4 данной ячейки 
# выглядит следующим образом b, matrix = betta(b), alpha(matrix)
b, a = betta(b), alpha(matrix)
x_prev = b
cnt = 0
while True:
    x = b + np.dot(a,x_prev)
    cnt += 1
    print(x)
    if norma(x, x_prev, 0.1) is True:
        x_prev = x
        print()
        continue
    else:
        print(x, cnt, (sum((x - x_prev) ** 2)) ** 0.5)
        break

[ 2.10264532  2.93353576 -7.12243215  7.31136602]

[ 3.30937297  2.83316256 -7.25925794  8.80350435]

[ 3.90009358  2.27395554 -7.43414919  9.16777527]

[ 4.1124443   2.11355483 -7.1893643   9.17481535]

[ 4.08765357  1.99227246 -7.07934493  9.12197263]

[ 4.05960785  1.97692601 -7.01681059  9.04230857]

[ 4.02059031  1.98233282 -6.99109621  9.01334563]
[ 4.02059031  1.98233282 -6.99109621  9.01334563] 7 0.055242041504722124


In [126]:
import numpy as np
matrix = np.array(A)
b = np.array(B)
n = 4

In [127]:
alpha(matrix)

array([[ 0.        , -0.08333333, -0.16666667,  0.375     ],
       [-0.22222222,  0.        , -0.2962963 , -0.22222222],
       [ 0.21052632, -0.42105263,  0.        , -0.31578947],
       [ 0.30769231,  0.38461538, -0.23076923,  0.        ]])

In [128]:
betta(b)

array([-0.375     ,  2.81481481, -4.15789474,  5.38461538])

In [129]:
# метод зейделя
x_prev = betta(b)
cnt = 0
x = betta(b)
while True:
    cnt += 1
    for i in range(len(x)):
        x[i] = betta(b)[i] + (x[0] * alpha(matrix)[i][0]) + (x[1] * alpha(matrix)[i][1]) + \
                    (x[2] * alpha(matrix)[i][2]) + (x[3] * alpha(matrix)[i][3])

    if norma(x, x_prev, 0.1) is True:
            x_prev = copy_b(x)
            print()
            print(x)
            continue
    else:
        print(x, cnt, (sum((x - x_prev) ** 2)) ** 0.5)
        break


[ 2.10264532  2.38294791 -6.41898391  8.42940558]

[ 3.65727875  2.03080612 -6.90493513  8.88445777]

[ 3.93826034  2.01122861 -6.98123864  8.98099233]
[ 3.98880951  2.00115178 -6.99683843  8.99627017] 4 0.05597791651536611
